### ISSUE TITLE
Metric Converter

### ISSUE THREAD

**Issue by Tuscann** [SoftUni/Programming-Basics-Resources#2]
https://github.com/SoftUni/Programming-Basics-Resources/blob/master/Java/Solutions/3.1.%20SimpleConditions/MetricConverter.java

https://judge.softuni.bg/Contests/Practice/Index/152#7 - 98/100
Има един тест който не се покрива от това решение. 

https://softuni.bg/forum/17445/java-problem-programmning-basic-simple-conditional-statements-metric-converter  - поправен код + обсъждане

**Comment by udarensamolet** [comment]
Fixed.
